name: Validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github

      - name: Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check --diff
